on:
  workflow_dispatch: 
  push:
    branches:
    - main
    
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Install Deps
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        make clean html
    - name: Deploy
      run: |
        echo "Deploying to NTNU file server"
        
      
