on:
  workflow_dispatch: 
  push:
    branches:
    - main
    
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
    - run: |
        sudo apt-get install sshpass -y
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install Deps
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        make clean html
    - name: Deploy
      env:
         SCP_USERNAME: ${{ secrets.USERNAME }}
         SCP_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        echo "Deploying to NTNU file server" >> github.txt
        sshpass -p ${SCP_PASSWORD} scp -prq ./github.txt ${SCP_USERNAME}:/public_html/idata2302/
      
